### ISSUE TITLE
using tagOrID for canvas

### ISSUE THREAD

**Issue by sl1200mk2** [aplsimple/baltip#1]
Hi,
I'm trying your package in my distribution and it's very easy to work with and works well with my version of Tk (8.7).

Would it be possible to use a canvas tag as widgetpath?

many thanks in advance,
best regards

**Comment by aplsimple** [comment]
Implemented in v1.2.0
Seen in demo
 https://github.com/aplsimple/baltip/releases/download/baltip-1.2/baltip-1.2.mp4

**Comment by sl1200mk2** [comment]
it works like a charm.
thanks

++
