### ISSUE TITLE
-on option is not global

### ISSUE THREAD

**Issue by sl1200mk2** [aplsimple/baltip#2]
Hi,
maybe I use it the wrong way... but as at tip creation the local -on value is set to the string length of his text, it does not take account of the global -on value.
if line 111 is :
    set my::ttdata(on,$w) $my::ttdata(on)
newly created tip take account of global -on value.

hope it's clear...
++

**Comment by aplsimple** [comment]
Hi Nicolas,

Thank you for your notice, proposal and kind words.

The 111 line would be corrected this way:

  set my::ttdata(on,$w) [expr {[string length $text] && $my::ttdata(on)}]


As for canvas, I think there will be no problems with its tooltip. I'll try
and make this feature soon, text tag being a pattern for this.

Also I am going to make tooltips for tabs of ttk::notebook.

Regards,
Alex

**Comment by aplsimple** [comment]
111 line corrected & ttk::notebook's tip added.
Seen in demo
https://github.com/aplsimple/baltip/releases/download/baltip-1.2/baltip-1.2.mp4

**Comment by sl1200mk2** [comment]
Hi,
it works very fine, thanks
